apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels: 
    app.kubernetes.io/name: myfirstpod
spec:
  containers:
  - name: myfirstpod
    image: vishnthirda/pythonimage:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
